### ISSUE TITLE
Couldn't start rails server when following instructions

### ISSUE THREAD

**Issue by noqcks** [Andrew-Max/try_rails_presentation#1]
I followed the instructions and wasn't able to access the project on `http://localhost:3000/` because there was no bin folder, I suspect. I had to run `$ rake rails:update:bin` from inside the project folder or `$ rails new try_rails_presentation -s` from the same directory as the project folder before I could then run `rails s` to access localhost.

Would you mind if I cleaned up some of the setup instructions and sent you a pull request?

**Comment by Andrew-Max** [comment]
@noqcks my apologies for missing this. Hope you were able to get some use out this. I cleaned this up so the app should be usable again.
